### ISSUE TITLE
Hopefully, create entities can be supported as well

### ISSUE THREAD

**Issue by MeiyuanaQ** [RogoShum/BruteForceRenderingCulling#3]
Hopefully, create entities can be supported as well

**Comment by RogoShum** [comment]
The create utilizes the rendering approach of the vanilla, so theoretically it should be fully compatible. If there are any compatibility issues, please describe the game version, mod version, and provide screenshots if possible.

**Comment by Sshmoob** [comment]
I think they were asking if support could be added for culling Create mod blocks, not if you could fix any rendering issues with them, because as far as I know, there aren't any.
As of right now, this mod doesn't cause any rendering issues with Create, it also doesn't cull anything from Create.

Also, unless you meant something else when you said "create utilizes the rendering approach of vanilla", Create uses a built-in library mod called flywheel to render it's blocks rather than the vanilla block entity renderer, which is also probably why it's blocks don't get culled by this mod.
However, as I don't know how this mod works, I can't be sure if it would even be possible to cull block entities rendered through flywheel the same way as other block entities are culled by this mod, and I know other entity culling mods don't cull Create's block entities either.
